// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlou9QCyI3LoflP21stc0rv-l9zPX-OVo',
    appId: '1:427705640852:web:b1632c91be5434f4331181',
    messagingSenderId: '427705640852',
    projectId: 'galleryapp-e362e',
    authDomain: 'galleryapp-e362e.firebaseapp.com',
    storageBucket: 'galleryapp-e362e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwmFQnn7N3H4WSLmzsakdvLsyeyTaK0Hs',
    appId: '1:427705640852:android:2de3624f39241ee2331181',
    messagingSenderId: '427705640852',
    projectId: 'galleryapp-e362e',
    storageBucket: 'galleryapp-e362e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlqDVAKP_dS3I3A_tBsjTH9UDHfqWk8Vw',
    appId: '1:427705640852:ios:86e000596a91b919331181',
    messagingSenderId: '427705640852',
    projectId: 'galleryapp-e362e',
    storageBucket: 'galleryapp-e362e.appspot.com',
    iosClientId: '427705640852-r79q9tcuh6k5bq3v5gpdsmhq7n0bc1hi.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlqDVAKP_dS3I3A_tBsjTH9UDHfqWk8Vw',
    appId: '1:427705640852:ios:86e000596a91b919331181',
    messagingSenderId: '427705640852',
    projectId: 'galleryapp-e362e',
    storageBucket: 'galleryapp-e362e.appspot.com',
    iosClientId: '427705640852-r79q9tcuh6k5bq3v5gpdsmhq7n0bc1hi.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyFlutter',
  );
}
